ignores:
  # Smart contracts
  - '@chainlink/contracts'
  - '@openzeppelin/contracts'
  - '@typechain/ethers-v6'
  - operator-filter-registry

  # Prettier
  - '@trivago/prettier-plugin-sort-imports'
  - prettier-plugin-solidity

  # Tests
  - '@types/mocha'

  # CI
  - '@evilmartians/lefthook'
  - depcheck
  - rimraf
