[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
solc = "0.8.19"

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config