# Foundry config reference: https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = "src"
out = "artifacts"
libs = ["lib"]
solc = "0.8.20"
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [{ access = "read", path = "./test/datasets" }]

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
