# Foundry config reference: https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
bytecode_hash = "none"
cbor_metadata = false
evm_version = "paris"
fs_permissions = [{ access = "read", path = "./test/datasets" }]
libs = ["lib"]
optimizer = true
optimizer_runs = 200
out = "artifacts"
solc = "0.8.22"
src = "src"
remappings = [
    'ERC721A/=lib/ERC721A/contracts/',
    'chainlink/=lib/chainlink/contracts/src/v0.8/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'openzeppelin/=lib/openzeppelin-contracts/contracts/',
    'operator-filter-registry/=lib/operator-filter-registry/src/',
    'solady/=lib/solady/src/',
    '@/=src/',
    '@test/=test/',
    '@script/=script/',
]

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[rpc_endpoints]
amoy = "${AMOY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }

[fmt]
bracket_spacing = true
line_length = 100
tab_width = 2

[profile.ci]
verbosity = 4

