name: Quality assessment
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  coverage:
    name: Compute the coverage with the tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run tests
        run: forge coverage --report=lcov -vvv
      - name: Run snapshot
        run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY
      - name: Send the coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
