name: Quality assessment
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    name: Lint with Solhint
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-foundry@main
      - name: Run Solhint
        run: pnpm lint

  fuzz:
    name: Test with intense fuzzing
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-foundry@main
      - name: Run fuzz testing
        run: forge test
        env:
          FOUNDRY_PROFILE: intense

  snapshot:
    name: Compute the gas snapshot
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-foundry@main
      - name: Run snapshot
        run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY

  coverage:
    name: Compute the coverage with the tests
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-foundry@main
      - name: Run tests with coverage
        run: forge coverage --report=lcov -vvv
      - name: Send the coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
