name: Quality assessment
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  eslint:
    name: Lint with ESLint
    runs-on: ubuntu-20.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-node@main
      - name: Lint with ESLint
        run: pnpm eslint

  solhint:
    name: Lint with Solhint
    runs-on: ubuntu-20.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-node@main
      - name: Lint with Solhint
        run: pnpm solhint

  gas:
    name: Runs the gas estimator with the tests
    runs-on: ubuntu-20.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-node@main
      - name: Run the tests
        run: pnpm test:gas
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}

  coverage:
    name: Compute the coverage with the tests
    runs-on: ubuntu-20.04
    steps:
      - name: Setup environment
        uses: pooky-labs/actions/setup-node@main
      - name: Run the tests in coverage mode
        run: pnpm test:coverage
      - name: Send the coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
